# Generated by Django 3.1.1 on 2020-09-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point1_longitude', models.FloatField(max_length=255)),
                ('point1_latitude', models.FloatField(max_length=255)),
                ('point2_longitude', models.FloatField(max_length=255)),
                ('point2_latitude', models.FloatField(max_length=255)),
            ],
        ),
    ]
